# Generated by Django 5.2.16 on 2026-07-30 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency_favorited_by', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('agency__isnull', True), ('listing__isnull', False)), models.Q(('agency__isnull', False), ('listing__isnull', True)), _connector='OR'), name='favorite_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('listing__isnull', False)), fields=('user', 'listing'), name='uniq_fav_listing'), models.UniqueConstraint(condition=models.Q(('agency__isnull', False)), fields=('user', 'agency'), name='uniq_fav_agency')],
            },
        ),
    ]
