# Generated by Django 5.2.16 on 2026-07-30 20:52

import apps.listings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('advert_code', models.PositiveIntegerField(default=apps.listings.models._new_advert_code, unique=True)),
                ('province', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('category', models.CharField(choices=[('appartamento', 'Appartamento'), ('casa', 'Casa'), ('villa', 'Villa'), ('ufficio', 'Ufficio'), ('negozio', 'Negozio'), ('capannone', 'Capannone')], max_length=20)),
                ('typology', models.CharField(choices=[('monolocale', 'Monolocale'), ('bilocale', 'Bilocale'), ('trilocale', 'Trilocale'), ('quadrilocale', 'Quadrilocale'), ('villa', 'Villa'), ('attico', 'Attico')], max_length=20)),
                ('contract', models.CharField(choices=[('vendita', 'Vendita'), ('affitto', 'Affitto')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('surface', models.PositiveIntegerField(help_text='m²')),
                ('n_rooms', models.PositiveSmallIntegerField()),
                ('floor_level', models.CharField(max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='listings/%Y/%m/')),
                ('external_url', models.URLField(blank=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
